Fix missing fields in MacOS build (#3344)
Summary:
MacOS has additional file fields that cause the build to fail:

```
      error[E0063]: missing fields `crtime` and `flags` in initializer of `fuse3::path::reply::FileAttr`
         --> monarch_extension/src/readonly_fuse.rs:375:24
          |
      375 |             .unwrap_or(FileAttr {
          |                        ^^^^^^^^ missing `crtime` and `flags`

      error[E0063]: missing fields `crtime` and `flags` in initializer of `fuse3::path::reply::FileAttr`
         --> monarch_extension/src/readonly_fuse.rs:161:8
          |
      161 |     Ok(FileAttr {
          |        ^^^^^^^^ missing `crtime` and `flags`

      error[E0063]: missing fields `crtime` and `flags` in initializer of `fuse3::path::reply::FileAttr`
         --> monarch_extension/src/chunked_fuse.rs:173:8
          |
      173 |     Ok(FileAttr {
          |        ^^^^^^^^ missing `crtime` and `flags`

      For more information about this error, try `rustc --explain E0063`.
```

on v0.4.0 this is:
```
 error[E0063]: missing fields `crtime` and `flags` in initializer of
      `fuse3::path::reply::FileAttr`
        --> monarch_extension/src/chunked_fuse.rs:83:8
         |
      83 |     Ok(FileAttr {
         |        ^^^^^^^^ missing `crtime` and `flags`

      For more information about this error, try `rustc --explain E0063`.
```

The first commit was tested on top of v0.4.0 (and thus can be cherry-picked into the tagged v0.4.0). The second was necessary on top of main. All changes are guarded on MacOS builds so no behavior should change for other platforms.

Pull Request resolved: https://github.com/meta-pytorch/monarch/pull/3344

Reviewed By: shayne-fletcher

Differential Revision: D100649669

Pulled By: dulinriley

fbshipit-source-id: a3f4112490992e425b4e85e17cdcc776dd5cea7e