Fix leftover configuration from test_config.py (#1971)
Summary:
Pull Request resolved: https://github.com/meta-pytorch/monarch/pull/1971

Python tests on github failing with:
```
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value:
Server(Listen(Tcp([::1]:0),
Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }))
```
It is caused by the default transport for tests changing from unix -> tcp.
It's not clear what caused this change, but probably a new test was added that changed
the pytest-split groups.

Make sure test_config.py resets to the default state when it is done.

Reviewed By: rusch95, shayne-fletcher

Differential Revision: D87664159

fbshipit-source-id: d8d1279d7909cf487df27500ceba56bc93e820c0