Remove deprecated await on proc_mesh/spawn calls in examples (#1406)
Summary:
Pull Request resolved: https://github.com/meta-pytorch/monarch/pull/1406

Fix Monarch examples broken by removal of DeprecatedNotAFuture in D82835567.

D82835567 removed the `DeprecatedNotAFuture` compatibility shim that provided fake `__await__()` methods on `ProcMesh` and `ActorMesh` objects.

With the shim removal, these examples started failing with:
```
TypeError: object ActorMesh can't be used in 'await' expression
```

This diff removes the incorrect `await` keywords.

Reviewed By: dulinriley

Differential Revision: D83138346

fbshipit-source-id: 83b32110c5e68b180c593499684936ae5cc6ce9d