Handle supervision events on work error (#93)
Summary:
Pull Request resolved: https://github.com/pytorch-labs/monarch/pull/93

We found that calling __test_panic on StreamActor does not propagate the rust stack trace back to the client. We expect to see a stack trace of the panic like
```
buck-out/v2/gen/fbcode/8afb8725dd81c3e5/monarch/python/tests/__test_controller__/test_controller#link-tree/monarch/python/tests/test_controller.py Actor mesh_0_worker[0].worker[1] crashed on unix!hdgSUkuhmycaIwwua4m2I7sI, check the host log for details
Traceback of the failure on worker (most recent call last):
  File "<unknown>", line None, in serving mesh_0_worker[0].worker[1]: panic: __test_panic called
  File "<unknown>", line None, in panicked at fbcode/monarch/monarch_messages/src/worker.rs:332:21
  File "<unknown>", line None, in    0: <unknown>
  File "<unknown>", line None, in    1: std::panicking::rust_panic_with_hook
  File "<unknown>", line None, in    2: <unknown>
  File "<unknown>", line None, in    3: std::sys::backtrace::__rust_end_short_backtrace::<std::panicking::begin_panic_handler::{closure#0}, !>
  File "<unknown>", line None, in    4: rust_begin_unwind
  File "<unknown>", line None, in    5: core::panicking::panic_fmt
  File "<unknown>", line None, in    6: <monarch_messages::worker::ResolvableFunction>::panic_if_requested
  File "<unknown>", line None, in    7: <unknown>
  File "<unknown>", line None, in    8: <unknown>
  File "<unknown>", line None, in    9: <monarch_worker::stream::StreamActor as hyperactor::actor::Handler<monarch_worker::stream::StreamMessage>>::handle::{closure#0}
  File "<unknown>", line None, in   10: <unknown>
  File "<unknown>", line None, in   11: <core::panic::unwind_safe::AssertUnwindSafe<<hyperactor::proc::Instance<monarch_worker::stream::StreamActor>>::run::{closure#0}> as core::future::future::Future>::poll
  File "<unknown>", line None, in   12: <tracing::instrument::Instrumented<<hyperactor::proc::Instance<monarch_worker::stream::StreamActor>>::serve::{closure#0}::{closure#0}> as core::future::future::Future>::poll
  File "<unknown>", line None, in   13: <unknown>
  File "<unknown>", line None, in   14: <tokio::runtime::task::trace::Root<hyperactor::panic_handler::with_backtrace_tracking<<hyperactor::proc::Instance<monarch_worker::stream::StreamActor>>::serve::{closure#0}>::{closure#0}> as core::future::future::Future>::poll
  File "<unknown>", line None, in   15: <pyo3::marker::Python>::allow_threads::<(), <monarch_worker::stream::StreamActor as hyperactor::actor::Actor>::spawn_server_task<hyperactor::panic_handler::with_backtrace_tracking<<hyperactor::proc::Instance<monarch_worker::stream::StreamActor>>::serve::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}::{closure#0}::{closure#0}>
  File "<unknown>", line None, in   16: tokio::runtime::context::runtime_mt::exit_runtime::<<monarch_worker::stream::StreamActor as hyperactor::actor::Actor>::spawn_server_task<hyperactor::panic_handler::with_backtrace_tracking<<hyperactor::proc::Instance<monarch_worker::stream::StreamActor>>::serve::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}, ()>
  File "<unknown>", line None, in   17: tokio::runtime::scheduler::multi_thread::worker::block_in_place::<<monarch_worker::stream::StreamActor as hyperactor::actor::Actor>::spawn_server_task<hyperactor::panic_handler::with_backtrace_tracking<<hyperactor::proc::Instance<monarch_worker::stream::StreamActor>>::serve::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}, ()>
  File "<unknown>", line None, in   18: <tokio::runtime::task::trace::Root<<monarch_worker::stream::StreamActor as hyperactor::actor::Actor>::spawn_server_task<hyperactor::panic_handler::with_backtrace_tracking<<hyperactor::proc::Instance<monarch_worker::stream::StreamActor>>::serve::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}> as core::future::future::Future>::poll
  File "<unknown>", line None, in   19: std::sys::backtrace::__rust_begin_short_backtrace::<<monarch_worker::stream::StreamActor as hyperactor::actor::Actor>::spawn_server_task<hyperactor::panic_handler::with_backtrace_tracking<<hyperactor::proc::Instance<monarch_worker::stream::StreamActor>>::serve::{closure#0}>::{closure#0}>::{closure#0}, ()>
  File "<unknown>", line None, in   20: <unknown>
  File "<unknown>", line None, in   21: <unknown>
  File "<unknown>", line None, in   22: start_thread
  File "<unknown>", line None, in              at /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/nptl/pthread_create.c:434:8
  File "<unknown>", line None, in   23: __clone3
  File "<unknown>", line None, in              at /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81:0
  File "<unknown>", line None, in
RuntimeError: Actor mesh_0_worker[0].worker[1] crashed on unix!hdgSUkuhmycaIwwua4m2I7sI, check the host log for details
```
but instead see an unhelpful
```
processing error: mesh_0_worker[1].worker[0]: recv mesh_0_worker[1].worker[0][1029]: channel closed
```
This was caused by WorkerActor handling supervision events by exiting the process, but even when it does not do this, errors from handling messages once child StreamActors are down will shadow supervision events from child StreamActors. If an Actor encounters an error, we may want to check if there are supervision events available in it's receiver as those may be the root cause of the error

Reviewed By: moonli

Differential Revision: D75490478

fbshipit-source-id: f4c50c2f05f8021947a902fc0f61a84ec77d9bb1