Avoid panic in Drop for PythonActorMesh (#680)
Summary:
Pull Request resolved: https://github.com/pytorch-labs/monarch/pull/680

There was a panic happening whenever a previously stopped proc mesh was
being dropped:
```
thread '<unnamed>' panicked at fbcode/monarch/monarch_hyperactor/src/actor_mesh.rs:394:33:
called `Result::unwrap()` on an `Err` value: EmptyCellError
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <monarch_hyperactor::actor_mesh::PythonActorMesh as core::ops::drop::Drop>::drop
   4: <pyo3::pycell::impl_::PyClassObject<monarch_hyperactor::actor_mesh::PythonActorMesh> as pyo3::pycell::impl_::PyClassObjectLayout<monarch_hyperactor::actor_mesh::PythonActorMesh>>::tp_dealloc
```

This was luckily ignored by pytest and considered a test pass, but it still messes up logs
and raises a pyo3.Panic exception.
It happened because the `stop()` method was taking the inner reference, so `borrow().unwrap()`
would panic.

Reviewed By: moonli

Differential Revision: D79200358

fbshipit-source-id: 83181ba367804054e43b47ba2d8fbecdbc6d4304