Fixes truncation logic (#1895)
Summary:
Pull Request resolved: https://github.com/meta-pytorch/monarch/pull/1895

During Monarch application development, we were seeing obscure error messages like:

```
[-]E1114 10:19:45.387346 338777 hyperactor/src/panic_handler.rs:47] panic at hyperactor_mesh/src/logging.rs:708:42, stacktrace:   0: std::panicking::update_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: __rustc::rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic
   7: hyperactor_mesh::logging::StreamFwder::start_with_writer::{{closure}}
   8: tokio::runtime::task::core::Core<T,S>::poll
   9: tokio::runtime::task::harness::Harness<T,S>::poll
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run
  12: tokio::runtime::context::scoped::Scoped<T>::set
  13: tokio::runtime::context::runtime::enter_runtime
  14: tokio::runtime::scheduler::multi_thread::worker::run
  15: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  16: tokio::runtime::task::core::Core<T,S>::poll
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: tokio::runtime::blocking::pool::Inner::run
  19: std::sys::backtrace::__rust_begin_short_backtrace
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}
  21: std::sys::pal::unix::thread::Thread::new::thread_start
  22: start_thread
  23: __clone3
thread 'tokio-runtime-worker' panicked at hyperactor_mesh/src/logging.rs:708:42:
assertion failed: self.is_char_boundary(new_len)
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

[0]E1114 10:19:45.385381 370095 hyperactor/src/panic_handler.rs:47] panic at hyperactor_mesh/src/logging.rs:708:42, stacktrace: 0: std::panicking::update_hook::{{closure}}
1: std::panicking::rust_panic_with_hook
2: std::panicking::begin_panic_handler::{{closure}}
3: std::sys::backtrace::__rust_end_short_backtrace
4: __rustc::rust_begin_unwind
5: core::panicking::panic_fmt
6: core::panicking::panic
7: hyperactor_mesh::logging::StreamFwder::start_with_writer::{{closure}}
8: tokio::runtime::task::core::Core<T,S>::poll
9: tokio::runtime::task::harness::Harness<T,S>::poll
10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
11: tokio::runtime::scheduler::multi_thread::worker::Context::run
12: tokio::runtime::context::scoped::Scoped<T>::set
13: tokio::runtime::context::runtime::enter_runtime
14: tokio::runtime::scheduler::multi_thread::worker::run
15: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
16: tokio::runtime::task::core::Core<T,S>::poll
17: tokio::runtime::task::harness::Harness<T,S>::poll
18: tokio::runtime::blocking::pool::Inner::run
19: std::sys::backtrace::__rust_begin_short_backtrace
20: core::ops::function::FnOnce::call_once{{vtable.shim}}
21: std::sys::pal::unix::thread::Thread::new::thread_start
22: start_thread
23: __clone3
```

The issue ended up being due to truncation in logging not correctly. Panics were being caused due to string truncation happening without respecting UTF-8 character boundaries. Therefore when truncation would land in the middle of a multi-byte character (like emojis or chinese text), Rust would pannic with `assertion failed: self.is_char_boundary(new_len)`.

We fix truncation logic in a few places: logging.rs, data.rs to verify char boundaries.

Reviewed By: vidhyav

Differential Revision: D87102794

fbshipit-source-id: da83308278bbc234d661e14f87dd99f5e72370f2