Update erased-serde from 0.3.31 to 0.4.9
Summary:
Only fbcode/asic/hargow and fbcode/common/rust/slog_scuba need to remain on 0.3, due to their use of slog's "nested-values" feature.

```lang=log,counterexample
error[E0053]: method `as_serde` has an incompatible type for trait
   --> fbcode/asic/hargow/lib/src/scuba.rs:233:9
    |
233 |         fn as_serde(&self) -> &dyn erased_serde::Serialize {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected trait `erased_serde::ser::Serialize`, found trait `erased_serde::Serialize`
    |
note: two different versions of crate `erased_serde` are being used; two types coming from two different versions of the same crate are different types even if they look the same
   --> third-party/rust/vendor/erased-serde-0.4.9/src/ser.rs:63:1
    |
    = note: this is the found trait `erased_serde::Serialize`
   --> third-party/rust/vendor/erased-serde-0.3.31/src/ser.rs:52:1
    |
    = note: this is the expected trait `erased_serde::ser::Serialize`
    |
   ::: fbcode/asic/hargow/lib/src/asic_directory.rs:4:5
    |
  4 | use hargow_common::organization::Organization;
    |     ------------- one version of crate `erased_serde` used here, as a dependency of crate `slog`
    |
   ::: fbcode/asic/hargow/lib/src/scuba.rs:233:36
    |
233 |         fn as_serde(&self) -> &dyn erased_serde::Serialize {
    |                                    ------------ one version of crate `erased_serde` used here, as a direct dependency of the current crate
    = help: you can use `cargo tree` to explore your dependency tree
```

```lang=log,counterexample
error[E0053]: method `as_serde` has an incompatible type for trait
  --> fbcode/common/rust/slog_scuba/tests/lib.rs:32:5
   |
32 |     fn as_serde(&self) -> &dyn erased_serde::Serialize {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected trait `erased_serde::ser::Serialize`, found trait `erased_serde::Serialize`
   |
note: two different versions of crate `erased_serde` are being used; two types coming from two different versions of the same crate are different types even if they look the same
  --> third-party/rust/vendor/erased-serde-0.4.9/src/ser.rs:63:1
   |
   = note: this is the found trait `erased_serde::Serialize`
  --> third-party/rust/vendor/erased-serde-0.3.31/src/ser.rs:52:1
   |
   = note: this is the expected trait `erased_serde::ser::Serialize`
   |
  ::: fbcode/common/rust/slog_scuba/tests/lib.rs:9:5
   |
 9 | use slog::o;
   |     ---- one version of crate `erased_serde` used here, as a dependency of crate `slog`
...
32 |     fn as_serde(&self) -> &dyn erased_serde::Serialize {
   |                                ------------ one version of crate `erased_serde` used here, as a direct dependency of the current crate
   = help: you can use `cargo tree` to explore your dependency tree
```

Reviewed By: diliop

Differential Revision: D86491220

fbshipit-source-id: 73e0070b11332bfd22acbd33ceff2d7a14bcab26