Turn on tokio time features for monarch_tensor_worker::stream tests (#1894)
Summary:
Pull Request resolved: https://github.com/meta-pytorch/monarch/pull/1894

Fixing test breakages like:
```
thread 'worker-stream' panicked at fbcode/monarch/hyperactor/src/clock.rs:293:9:
A Tokio 1.x context was found, but timers are disabled. Call `enable_time` on the runtime builder to enable timers.
```
in stream.rs
This was caused by a new usage of `tokio::time::timeout` via `RealClock.timeout`. But
we use this in many places and i

Reviewed By: colin2328

Differential Revision: D87099251

fbshipit-source-id: ff6d1d12f09c41eca250f24c2649ef2a5404df7a