: disable test_network
Summary:
D76846286 landed on master, does not appear in the github commit stream and breaks test_network.py with 

```
 =========================== short test summary info ============================                                                          
 FAILED python/tests/tools/test_network.py::TestNetwork::test_network_ipv4_fallback - AttributeError: module 'monarch.tools.network' has n$
 FAILED python/tests/tools/test_network.py::TestNetwork::test_network_ipv6 - AttributeError: module 'monarch.tools.network' has no attribu$
 Traceback (most recent call last):                                                                                                        
   File "/home/ec2-user/actions-runner/_work/monarch/monarch/test-infra/.github/scripts/run_with_env_secrets.py", line 102, in <module>    
 =========== 2 failed, 50 passed, 564 deselected, 7 warnings in 4.20s ===========                                                          

```

Differential Revision: D84913069