Add missing docstring to example for sphinx documentation (#2218)
Summary:
Pull Request resolved: https://github.com/meta-pytorch/monarch/pull/2218

Fixing documentation build error:
```
sphinx.errors.ExtensionError: Could not find docstring in file
"/meta-pytorch/monarch/docs/source/examples/grpo_sim.py".
A docstring is required by sphinx-gallery unless the file is ignored by "ignore_pattern"
```
Added a docstring to this file, which is the only file in examples missing it.

Reviewed By: thomasywang

Differential Revision: D89931402

fbshipit-source-id: 8297cac63062e478e3a4b40ad58bccf29e697ec4