Use Synthetic trace sender for endpoint spans (#3681)
Summary:
Pull Request resolved: https://github.com/meta-pytorch/monarch/pull/3681

Instead of trying to hack around `tracing` spans to create user spans indicating when an endpoint is being called and when it gets a response, which can lead to bugs like
```
thread '<unnamed>' (1774) panicked at third-party/rust/vendor/tracing-subscriber-0.3.23/src/registry/sharded.rs:306:32:
tried to clone Id(788131309179371521), but no span exists with that ID
This may be caused by consuming a parent span (`parent: span`) rather than borrowing it (`parent: &span`).
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We should just use the synthetic sender to directly send span events to `TraceDispatcher`

Reviewed By: shayne-fletcher

Differential Revision: D103010060

fbshipit-source-id: 823b57069d27b2922cc50cd69f6b7aea7b726f13